name: Deploy to AWS S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_CICD_USER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_CICD_USER_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync files to S3
      uses: aws-actions/s3-sync-action@v2
      with:
        source-dir: 'dist'
        destination-bucket: 'your-s3-bucket-name'
        destination-prefix: 'your-folder-prefix'
        delete-removed: true

    - name: Invalidate CloudFront cache
      uses: chetan/invalidate-cloudfront-action@v1
      with:
        distribution-id: 'your-cloudfront-distribution-id'
        paths: '/*'
      env:
        AWS_REGION: 'us-east-1'
        AWS_CICD_USER_ACCESS_KEY_ID: ${{ secrets.AWS_CICD_USER_ACCESS_KEY_ID }}
        AWS_CICD_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_CICD_USER_SECRET_ACCESS_KEY }}
